"""Añadir campo device a la tabla amigos

Revision ID: dfa36864f720
Revises: addcb737f7eb
Create Date: 2026-10-06 17:02:09.498263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa36864f720'
down_revision = 'addcb737f7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.drop_column('device')

    # ### end Alembic commands ###
